### ISSUE TITLE
Cannot Find Module Quarry

### ISSUE THREAD

**Issue by GriffinS20** [Ameliorate/DevotedBot#2]
Traceback (most recent call last):
  File "start.py", line 9, in <module>
    from quarry.net.client import ClientProtocol, ClientFactory
ImportError: No module named 'quarry'

**Comment by Ameliorate** [comment]
Please see [INSTALLING.md](https://github.com/Ameliorate/DevotedBot/blob/master/INSTALLING.md) and [PIP-REQUIREMENTS.txt](https://github.com/Ameliorate/DevotedBot/blob/master/PIP-REQUIREMENTS.txt).
